@url = http://localhost:7071/api
# @url = https://pokemon-browser.azurewebsites.net/api

@name = pikachu

### Get pokemon by name
GET {{url}}/getByName?name={{name}}

### Get random pokemon
GET {{url}}/getRandom
